spring:
  application:
    name: hotel-booking
springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG