spring:
  application:
    name: hotel-booking
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG